// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

/*
Package contract is a generated protocol buffer package.

It is generated from these files:
	hello.proto

It has these top-level messages:
	Person
	Request
*/
package contract

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Gender int32

const (
	Gender_MALE   Gender = 0
	Gender_FEMALE Gender = 1
)

var Gender_name = map[int32]string{
	0: "MALE",
	1: "FEMALE",
}
var Gender_value = map[string]int32{
	"MALE":   0,
	"FEMALE": 1,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}
func (Gender) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Person struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	FirstName  string `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	MiddleName string `protobuf:"bytes,3,opt,name=middle_name,json=middleName" json:"middle_name,omitempty"`
	LastName   string `protobuf:"bytes,4,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Email      string `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	Phone      string `protobuf:"bytes,6,opt,name=phone" json:"phone,omitempty"`
	Gender     Gender `protobuf:"varint,7,opt,name=gender,enum=contract.Gender" json:"gender,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Person) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Person) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Person) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Person) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_MALE
}

type Request struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "contract.Person")
	proto.RegisterType((*Request)(nil), "contract.Request")
	proto.RegisterEnum("contract.Gender", Gender_name, Gender_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HelloService service

type HelloServiceClient interface {
	Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Person, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := grpc.Invoke(ctx, "/contract.HelloService/Hello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HelloService service

type HelloServiceServer interface {
	Hello(context.Context, *Request) (*Person, error)
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contract.HelloService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Hello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "contract.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _HelloService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xcd, 0x5c, 0xb3, 0xed, 0x4d, 0xc6, 0x0c, 0x0a, 0x55, 0x51, 0xcb, 0x4e, 0x45, 0xa4,
	0x87, 0x79, 0xf5, 0xe2, 0x60, 0xce, 0x83, 0xca, 0xa8, 0x1f, 0x40, 0x62, 0xf3, 0xdc, 0x02, 0x6d,
	0x52, 0xd3, 0x28, 0xec, 0x33, 0xfa, 0xa5, 0xa4, 0x2f, 0x1b, 0x8a, 0xa7, 0xe4, 0xfd, 0x7e, 0x2f,
	0xc9, 0xcb, 0x1f, 0x86, 0x6b, 0x2c, 0x4b, 0x9b, 0xd5, 0xce, 0x7a, 0x2b, 0xfa, 0x85, 0x35, 0xde,
	0xc9, 0xc2, 0x4f, 0xbe, 0x19, 0xf0, 0x25, 0xba, 0xc6, 0x1a, 0x31, 0x82, 0x8e, 0x56, 0x31, 0x4b,
	0x58, 0x3a, 0xc8, 0x3b, 0x5a, 0x89, 0x73, 0x80, 0x77, 0xed, 0x1a, 0xff, 0x6a, 0x64, 0x85, 0x71,
	0x87, 0xf8, 0x80, 0xc8, 0xb3, 0xac, 0x50, 0x5c, 0xc2, 0xb0, 0xd2, 0x4a, 0x95, 0x18, 0xfc, 0x3e,
	0x79, 0x08, 0x88, 0x1a, 0xce, 0x60, 0x50, 0xca, 0xdd, 0xf1, 0x2e, 0xe9, 0x7e, 0x0b, 0x48, 0x1e,
	0x41, 0x84, 0x95, 0xd4, 0x65, 0x1c, 0x91, 0x08, 0x45, 0x4b, 0xeb, 0xb5, 0x35, 0x18, 0xf3, 0x40,
	0xa9, 0x10, 0x29, 0xf0, 0x15, 0x1a, 0x85, 0x2e, 0xee, 0x25, 0x2c, 0x1d, 0x4d, 0xc7, 0xd9, 0x6e,
	0xfc, 0x6c, 0x41, 0x3c, 0xdf, 0xfa, 0xc9, 0x09, 0xf4, 0x72, 0xfc, 0xf8, 0xc4, 0xc6, 0xff, 0xff,
	0xcd, 0xd5, 0x05, 0xf0, 0xd0, 0x2c, 0xfa, 0xd0, 0x7d, 0xba, 0x7b, 0x9c, 0x8f, 0xf7, 0x04, 0x00,
	0xbf, 0x9f, 0xd3, 0x9e, 0x4d, 0x6f, 0xe1, 0xe0, 0xa1, 0x4d, 0xe8, 0x05, 0xdd, 0x97, 0x2e, 0x50,
	0x5c, 0x43, 0x44, 0xb5, 0x38, 0xfc, 0x7d, 0x6d, 0x7b, 0xf7, 0xe9, 0x9f, 0x01, 0x42, 0x76, 0xb3,
	0x04, 0x8e, 0xb5, 0xcd, 0xd4, 0xc6, 0xc8, 0xc6, 0x6f, 0x2a, 0xd9, 0x38, 0x99, 0xad, 0xac, 0xab,
	0x8b, 0x59, 0xb4, 0x68, 0x97, 0x25, 0x7b, 0xe3, 0x94, 0xfc, 0xcd, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x77, 0x4c, 0x62, 0x78, 0x88, 0x01, 0x00, 0x00,
}
